activerecord-hackery/ransack

- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
This is a try at fixing #472 and it works for me. Arel's update now has an Arel::Nodes::Casted type instead of the original array, so NULL gets passed into the SQL statement. This should cover all cases, and an if statement has been placed so this only will apply for when the Arel::Nodes::Casted type is used.
> [472] Allow arrays to be received for custom ransacker

- CHANGELOG.md
- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
This is a fix for the last example in #472 in which filtering on a string field does not work in Arel >= 6. The test written passes with Arel 5 without the fix, and the fix allows the test to pass in Arel 6.
> Allow string arrays to be received for custom ransacker.

- CHANGELOG.md
- lib/ransack/constants.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
The TRUE_VALUES and FALSE_VALUES haven't been changed since the initial commit 294015309b03240c6a9a9aea69118a24d7f737ac , yet my removing the values that I have removed doesn't break any tests.
@ernie do you remember the purpose for the values I propose removing?
> Don't replace 0 and 1 with false and true, fixes #502

- .gitignore
- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
This failing test reproduces https://github.com/activerecord-hackery/ransack/issues/504
It's a much-simplified version of a ransacker in my application which worked in 1.5.1 and 1.6.0, but which fails in subsequent releases, including master, because of https://github.com/activerecord-hackery/ransack/commit/6c59e96adaa43f4e8141352f508b84a046343591 as explained in https://github.com/activerecord-hackery/ransack/issues/504
Disclaimer: This is the first time I've ever worked with ransack or arel in detail, and I'm not the one who wrote the ransacker in my app.  I'm just trying to upgrade to the latest ransack (1.6.3).
> Fix NoMethodError in casted_array_with_in_predicate?

- lib/ransack/nodes/attribute.rb
- lib/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
This is related to https://github.com/activerecord-hackery/ransack/issues/508 but I have another use case:
In my project I have Customer and Deal models. Customers have many Deals and each deal has `amount` attribute. I want to find customers which have made deals with total amount more than specified value for the last week. So my ransacker is:
```ruby
ransacker :sum_of_deals_last_week do |parent|
deals_table = Deal.arel_table
Arel::Nodes::Grouping.new(
deals_table
.project(Arel::Nodes::Sum.new([deals_table[:amount]]))
.group(deals_table[:customer_id])
.where(deals_table[:customer_id].eq(parent.table[:id])
.and(deals_table[:created_at].gteq(1.week.ago.to_date)
.and(deals_table[:created_at].lteq(Date.today))
)
).ast
)
end
```
And I can easily filter:
```ruby …
```
> Allow ransacker to have its arguments

- README.md
- lib/ransack/translate.rb
This simple pull request allow us to use I18n model names from ransack scope, not only from activerecord scope, similarly as for attribute names.
Background:
1. I need in attribute select different name for the base model as generally.
2. So is the using of I18n in ransack unified.
> Allow to use model name from I18n ransack scope

- CHANGELOG.md
- lib/ransack/predicate.rb
- spec/mongoid/configuration_spec.rb
- spec/ransack/configuration_spec.rb
Addressing https://github.com/activerecord-hackery/ransack/issues/32
> allowing ':wants_array' to be passed as 'false' in predicate options

- lib/ransack/adapters/active_record/context.rb
9e818cde introduced a bug by making an erroneous reference to `ActiveRecord::Associations::JoinDependency` in line 187. As this class lives inside an `ActiveRecord` module, that reference needs to be absolute in order to properly point at AR's class.
> Fix erroneous reference to AR class

- ransack.gemspec
Removed hardcoded "rails 4.2" dependency -- this prevents the branch from working with, for example, rails 4.2.1
> Allow any micro version in rails 4.2

- spec/ransack/adapters/active_record/base_spec.rb
When the database has `default_timezone = :local` (system time) and the Time.zone is set to elsewhere then `Date.current` does not match what the query produces for the stored timestamps.
Resolved by setting everything to UTC.
> Fix time-dependent test failure

- lib/ransack/adapters/active_record/3.0/context.rb
- lib/ransack/adapters/active_record/3.1/context.rb
- spec/ransack/search_spec.rb
- spec/support/schema.rb
This is a fix on top of my previous pull request #426 where I fixed one bug but potentially introduced another. :speak_no_evil: 
When a model with default scope was associated with conditions (`has_many :x, conditions: ...`), the default scope would overwrite the association conditions. This patch ensures that both sources of conditions are applied.
> Avoid overwriting association conditions with default scope in Rails 3

- lib/ransack/adapters/mongoid/base.rb
- lib/ransack/adapters/mongoid/context.rb
- lib/ransack/nodes/attribute.rb
Support referenced relations for mongoid in ransack is very difficult due to the fact that mongodb has no joins, therefore I guess might as well start with something that I have a workable solution to.
I have not written any specs for this PR yet, just to throw it out there to see if this is a good idea.
> Embedded Relations in Mongoid

- lib/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
This PR tries to resolve #299 
I think Ransack must recognize attribute\_name which includes `_and_` `_or_`.
My approach is:
If the model includes attribute\_name, Ransack should recognize it as one attribute\_name.
Please feedback this PR !!
> Fix handling attribute-name with `_and_` `_or_`

- lib/ransack.rb
- lib/ransack/adapters.rb
- lib/ransack/context.rb
- lib/ransack/nodes.rb
- lib/ransack/search.rb
Adapters overwrite each other, so they should not be required both
> ActiveRecord excludes Mongoid

- lib/ransack/adapters/active_record/ransack/constants.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/predicate_spec.rb
Escape mysql/pg `_` wildcard character.
> Escape underscore wildcard for pg and mysql.

- lib/ransack/nodes/sort.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
....
Hello guys, I found ransacker_args pretty cool, but I need to use same ransacker to sort fields.
Here some sample code for PostgreSQL hstore:
ransacker :dynamic_hstore, args: [:parent, :ransacker_args] do |parent, args|
column, field = args
Arel::Nodes::InfixOperation.new("->", Person.arel_table[column], Arel::Nodes.build_quoted(field))
end
s = Person.ransack(
c: [{
a: {
'0' => {
name: 'dynamic_hstore',
ransacker_args: ['hstore_column', 'example_field']
}
},
p: 'cont',
v: ['Some Value']
}],
s: {
'0' => {
'name' => 'dynamic_hstore',
'dir' => 'asc',
'ransacker_args' => ['hstore_column', 'example_field']
}
}
)
s.result.to_sql
=> SELECT "people".* FROM "people" WHERE ("people"."hstore_column" -> 'example_field' ILIKE '%Some Value%')  ORDER BY "people"."hstore_column" -> 'example_field' …
> Ransacker arguments sort

- lib/ransack/nodes/bindable.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
Aliased attributes on associations searches (e.g: `articles_content_cont`) did not work, I added a failing test and then implemented a fix.
> Fixes aliased attributes in association searches

- lib/ransack/adapters/active_record/base.rb
- lib/ransack/adapters/mongoid/base.rb
- lib/ransack/context.rb
- lib/ransack/nodes/condition.rb
- spec/mongoid/adapters/mongoid/base_spec.rb
- spec/mongoid/nodes/condition_spec.rb
- spec/mongoid/support/schema.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/nodes/condition_spec.rb
- spec/support/schema.rb
Ransack is great, but the query strings can get crazy pretty quickly, especially when querying associations. It would be really great to have aliases for ransack attributes.
It seems like people want this feature built into Ransack. See:
+ #39
+ #253 
+ #536
+ https://github.com/jhdavids8/ransack-abbreviator
This PR allows you to do this:
```ruby
class Author < ActiveRecord::Base
end
class Post < ActiveRecord::Base
belongs_to :author
ransack_alias :name, :title
ransack_alias :author, :author_first_name_or_author_last_name
end
puts Post.ransack(name_start: 'Fun').result.to_sql
puts Post.ransack(author_cont: 'Ray').result.to_sql
```
```sql
SELECT "posts".* FROM "posts"
WHERE ("posts"."title" LIKE 'Fun%')
SELECT "posts".* FROM "posts"
LEFT OUTER JOIN "authors" ON "authors"."id" = …
```
> Allow creating aliases for ransack attributes

- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
Allow passing block argument to the sort_link method:
```ruby
<%= sort_link(@q, :name, [:name, 'kind ASC']) do %>
<strong>Player Name</strong>
<% end %>
```
> Add block argument for sort_link

- lib/ransack/helpers/form_helper.rb
- lib/ransack/search.rb
`search_params` didn’t need this behavior because it’s using the `@params` variable that’s already ready for use
> Rails 5 params: instance_variable_get -> to_unsafe_h

- lib/ransack/adapters/active_record.rb
- lib/ransack/adapters/active_record/3.0/context.rb
- lib/ransack/adapters/active_record/3.1/context.rb
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/context.rb
- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- lib/ransack/adapters/mongoid/context.rb
- lib/ransack/context.rb
- lib/ransack/nodes/attribute.rb
- lib/ransack/nodes/condition.rb
- lib/ransack/nodes/sort.rb
- lib/ransack/predicate.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/helpers/form_helper_spec.rb
- spec/ransack/nodes/condition_spec.rb
When searching against attributes from a collection association (`has_many` / `:through` / `has_and_belongs_to_many`), a normal JOIN will include false positives when asking to exclude values (`!=`, `NOT IN`, `IS NOT NULL`) and another tuple is matched.
This is the basic case, see specs for details:
* A book exists with two tags: "medieval" and "fantasy"
* You search for books that are NOT "fantasy"
* The result would still include it, because it matches the other tag for NOT "fantasy"
In situations where this would happen, I've moved the `LEFT OUTER JOIN` into a subquery with inverted conditions. This is implemented with a correlated primary key which should help the query plan to avoid scanning entire tables in the subquery. The conditions now look like this:
```
WHERE root.id NOT IN ( …
```
> Respect negative conditions for collection associations

- lib/ransack/nodes/grouping.rb
- spec/ransack/nodes/grouping_spec.rb
We have a setup similar to http://ransack-demo.herokuapp.com/users/advanced_search.  We use ransackers + ransacker_args to create "virtual" attributes - by that I mean attributes that have the same name, but are passed different ransacker_args.  One scenario for us is total_donations_over_time, which is a ransacker that takes a date range as its ransacker_args.  We have "Total donations this year" and "Total donations last year" in our attributes dropdown, but they both map to total_donations_over_time.  Anyways, I found that subsequent conditions having the same attribute name, predicate, and value were getting removed by self.conditions.uniq! even if they had different ransacker_args.  This patch fixes the issue by passing a block to uniq!.
> Ensure conditions differing only by ransacker_args aren't filtered out by uniq!

- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
I tried to change `spec/support/schema.rb` and `spec/ransack/adapters/active_record/base_spec.rb` like below.
```rb
ransacker :array_users,                                                                                                
formatter: proc { |v| Person.where(id: v).map(&:id) } do |parent|                                                    
parent.table[:id]                                                                                                    
end   
```
```rb
it 'should function correctly when passing an array of ids' do                                                           
s = Person.ransack(array_users_in: [1, 2])                                                                               
expect(s.result.count).to be 2
end
```
Should be pass tests but …
> Fix returned value when several predicate.right

- README.md
- lib/ransack/helpers/form_builder.rb
- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
ref #672 
I add sort_url function.
This is return only url of sort_link.
Also, I add test code for sort_url.
> Add sort url

- lib/ransack/adapters/active_record/base.rb
- lib/ransack/adapters/mongoid/base.rb
- spec/mongoid/adapters/mongoid/base_spec.rb
- spec/mongoid/search_spec.rb
- spec/mongoid/support/schema.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
This fixes two bugs:
1. Subclasses were not properly inheriting their parents' Ransack
aliases in Mongoid because each class defined its very own set of
aliases.
2. In Active Record, Ransack aliases were defined in such a way that the
parent's (and grandparent's, etc.) aliases were overwritten by the
child, meaning that all aliases were ultimately kept on
ActiveRecord::Base. This has the unfortunate effect of enforcing
uniqueness of Ransack alias names across all models rather than per
model. Depending on the load order of models, earlier definitions of
an alias in other models would be clobbered.
> Allow Active Record Ransack aliases with the same name on different models

- lib/ransack.rb
- lib/ransack/adapters/active_record.rb
For avoiding autoloading these constants too soon.
This affect the initialization of Active Record.
Ref: https://github.com/rails/rails/issues/23589#issuecomment-229247727
> use `ActiveSupport.on_load` to hook into Active Record

- lib/ransack/adapters/mongoid.rb
In #719, the definition of `Ransack::SUPPORTS_ATTRIBUTE_ALIAS` has changed when
Active Record is loaded.
In the impact, `Ransack::SUPPORTS_ATTRIBUTE_ALIAS` in mongo adapter has become no longer be defined,
modify to defined in mongoid adapter.
Follow up to #719
> define `Ransack::SUPPORTS_ATTRIBUTE_ALIAS` to mongoid adapter

- CHANGELOG.md
- README.md
- lib/ransack/configuration.rb
- lib/ransack/helpers/form_helper.rb
- spec/mongoid/configuration_spec.rb
- spec/ransack/configuration_spec.rb
- spec/ransack/helpers/form_helper_spec.rb
This addition allows users to pass in their own up and down arrows. The default arrows remain the same. The user can pass in just one arrow, or both arrows.
Functionality is hand-tested with a codebase in production. Please let me know if you'd like any edits.
> Add customizable indicator arrows

- README.md
I often open this repo because I don't remember all predicates.
And for some predicates it was not obvious for me how to use it, so I had to search in repo.
I hope this section in README will be helpful for people like me, but probably need some help to make better description.
Also:
- `_eq_any` is same as `_in` ? (and `_not_eq_any` is same as `_not_in`?)
- What's the point to use `eq_all` ? If I use it as `col_eq: ["A", "B"]`, how something can be equal "A" and "B" at the same time?
- What's the point to use `gt_any`? If value in DB is greater then any then it's greater then smallest searchable value?
- Same with `gt_all` - if greater then all, then also greater then biggest
- If I do `start_all: ["A", "B"]`, anything can start with "A" and "B" at the same time?
> Add list of predicates to readme

- CHANGELOG.md
- README.md
- lib/ransack/configuration.rb
- lib/ransack/search.rb
- spec/ransack/adapters/active_record/base_spec.rb
There has been a lot of discussion about ways to get around Ransack converting scope values to booleans. Here are just a few places: #509, #593, #580, #566.  This PR specifically addresses the tests presented in #575.
An easy solution to this would be to simply stop making these conversions. But then we run the risk of breaking backwards compatibility. So instead of changing them, I've added a config option to turn them off.
It'd be easy to modify this to make the config option more granular. We could set it up for the user to specify what exact truthy/falsey values they would like converted, and use the default settings if this config is NOT specified. For example, instead of:
```
```
we could do this:
```
```
But I don't know if that level of detail is needed/desired. If being able to …
> Config option for turning off custom scope argument sanitization

- README.md
The [will_paginate](https://github.com/mislav/will_paginate) has been updated for Rails 5 so I think this verbiage can be removed from the README. Thanks!
> Update README remove Rails 5 and pagination [skip ci]

- .travis.yml
Gem install error
Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.
https://travis-ci.org/activerecord-hackery/ransack
> Remove Ruby 2.0 and Rails 4.2 test

- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/predicate_spec.rb
```
> Article.count
=> 31
> ids = Article.all.pluck(:id).sample(4)
=> [12, 28, 5, 22]
> Comment.where(article_id: ids).destroy_all
```
```
> Article.ransack('comments_id_null' => '1').result(distinct: true).count
=> 4 # OK
> Article.ransack('comments_id_null' => '0').result(distinct: true).count
=> 27 # OK 
```
```
> Article.ransack('comments_id_not_null' => '1').result(distinct: true).count
=> 31 # BAD
> Article.ransack('comments_id_not_null' => '0').result(distinct: true).count
=> 4 # OK
```
```
> puts Article.ransack('comments_id_not_null' => '1').result(distinct: true).to_sql
```
```
SELECT DISTINCT "articles".* 
FROM "articles" 
WHERE ('default_scope' = 'default_scope') 
AND ("articles"."id" NOT IN (
SELECT "comments"."article_id" 
FROM "comments" 
WHERE "comments"."article_id" = …
```
> Fix query of not_null with joining association 

- README.md
- lib/ransack/configuration.rb
- lib/ransack/helpers/form_helper.rb
- spec/ransack/configuration_spec.rb
- spec/ransack/helpers/form_helper_spec.rb
Currently if a field is not sorted then no icon is displayed. By default this behaviour will stay the same, however there is now the option of setting a `default_arrow` in the configuration which would be displayed on all sortable columns currently not sorted.
I could not find a sensible unicode character to do this, however bootstrap glyphicons / font awesome both have good options for it (`fa-sort` for example).
The default value of `default_arrow` is `nil` which keeps the current API exactly the same unless this configuration is changed.
> Add an optional default arrow for unsorted fields

- lib/ransack/helpers/form_helper.rb
fix bug in sort_link helper around argument extraction about sort fields with block.
> fix bug in sort_link helper around argument extraction about sort fields with block.

- lib/ransack/nodes/value.rb
Postgres otherwise handles the string that's passed down, except in the case that the user accidentally enters a string meant for a different attribute entirely. `to_f` converts it into zero, making it a valid database request.
```ruby
>> Table.search(column_eq: '1.5').result.count
>> Table.search(column_eq: 'foo').result.count
>> Table.search(column_eq: '100').result.count
```
> Cast Postgres money type to float

- lib/ransack.rb
Hello guys thanks for creating and maintaining this gem 😍 
Use lazy load hooks to hook on ActionController::Base:
- Calling directly `ActionController::Base` affects the initialization process (one of them being one that controls ActionController [configuration](https://github.com/rails/rails/blob/aa6bcbbac8517d5b077f21073e9902637d7c7157/actionpack/lib/action_controller/railtie.rb#L53-L67))
- As a result setting configuration inside an initializer (such as the asset_host), won't have any effect
> Use lazy load hooks to hook on ActionController::Base

- lib/ransack/adapters/active_record/3.0/context.rb
- lib/ransack/adapters/active_record/3.1/context.rb
- lib/ransack/adapters/active_record/base.rb
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/context.rb
- lib/ransack/adapters/mongoid/context.rb
- lib/ransack/adapters/mongoid/ransack/context.rb
- lib/ransack/configuration.rb
- lib/ransack/context.rb
- lib/ransack/nodes/grouping.rb
- lib/ransack/predicate.rb
- lib/ransack/translate.rb
Proof-of-concept for #819
These changes decreased memory usage by 96% 🚀 (1.3 MB to 58 KB)
```
Total allocated: 59848 bytes (1164 objects)
Total retained:  712 bytes (14 objects)
allocated memory by location
-----------------------------------
8048  ransack/lib/ransack/adapters/active_record/ransack/context.rb:11
7056  ransack/lib/ransack/adapters/active_record/context.rb:55
4080  ransack/lib/ransack/adapters/active_record/context.rb:49
3024  ransack/lib/ransack/adapters/active_record/context.rb:50
2872  ransack/lib/ransack/adapters/active_record/context.rb:254
2680  ransack/lib/ransack/adapters/active_record/context.rb:268
2680  ransack/lib/ransack/adapters/active_record/context.rb:271
allocated objects by location
-----------------------------------
102 …
```
> Improve memory usage

- ransack.gemspec
Please add comments / review before this is merged.
> Bump Polyamorous to 1.3.2 for Rails 5.2 support

- .travis.yml
- Gemfile
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/context.rb
- lib/ransack/constants.rb
- lib/ransack/helpers/form_builder.rb
Fixes #853. Closes #859, #849.
> Add support for Rails 5.2

- lib/ransack/adapters/active_record/ransack/constants.rb
The regexp `/([\\|\%|_|.])/` means `\` or `|` or `%` or `|` or `_` or `|` or `.`, which includes unwanted `|` character multiple times.
> Let escape_wildcards not escape '|'

- lib/ransack/adapters/active_record/context.rb
Fixes the following error:
protected method `alias_tracker' called for #<ActiveRecord::Associations::JoinDependency:0x0000000002fc3bc0>
The method is still protected in Rails 5.2 and so must be called via `send`.
> Fix build_joins on Rails 5.2.rc1

- lib/ransack/adapters/active_record/context.rb
I have run in to a small problem - in my project I have changed the definition of ActiveRecord::Base#columns to include virtual columns (computed columns). 
Example: if I have a User model with first_name and last_name, I create a virtual column full_name, which is concatenated first and last names. SQL looks like this:
```SQL
SELECT users.* FROM (SELECT *, (first_name || ' ' || last_name) AS full_name) AS users
```
This allows me to use full_name in WHERE, GROUP, ORDER BY clauses. After adding this column to ActiveRecord::Base#columns, #ransack method stops dropping "full_name_#{predicate}" keys from the params hash. But because later on it derives column type from schema_cache (which gets columns from the database), undefined method 'type' for nil is thrown.
Changing this to get columns …
> get column type from ActiveRecord::Base#columns

- lib/ransack/adapters/active_record/context.rb
Given a relation that has `#left_outer_joins` before calling `#search`,
```
Person.left_outer_joins(:article).search(article_name_cont: 'foo')
```
Ransack will perform a `LEFT OUTER JOIN` twice resulting into an invalid query.
Since Rails 5.x.x added a `left_outer_joins_values`, `Context#build` must take
the existing joins from there too before automagically adding them.
This mimics the behavior added at
https://github.com/rails/rails/blob/ef7b9b867b3c113bbbc7639b5d760a8f962a683c/activerecord/lib/active_record/relation/query_methods.rb#L943
@seanfcarroll @jonatack
> Fix left_outer_joins not being respected

- lib/ransack/adapters.rb
The reason can be found here: https://github.com/activeadmin/activeadmin/issues/4756
The solution is from @deivid-rodriguez in: https://github.com/activeadmin/activeadmin/issues/4756#issuecomment-275505455
> raise exception for unsupported adapters

- lib/ransack/adapters/active_record/context.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/spec_helper.rb
- spec/support/schema.rb
> Fix connection issue of multiple database

- lib/ransack/nodes/grouping.rb
Just browsing the code I noticed this odd-looking conditional. `detect` returns nil if no result is found, so no need to check it, just return it, right?
> Refactor conditional

- lib/ransack/adapters/active_record/3.0/compat.rb
- lib/ransack/adapters/mongoid/ransack/nodes/condition.rb
- lib/ransack/adapters/mongoid/ransack/visitor.rb
- lib/ransack/visitor.rb
I noticed a few places with the pattern:
```ruby
return nil unless nodes.size > 0
if nodes.size > 1
nodes.inject(&:and)
else
nodes.first
end
```
This can be simplfied to just:
```ruby
nodes.inject(&:and)
```
since `inject` returns the first element if the array only has one element, and `nil` if the array has no elements (which is exactly what the more verbose code is doing).
> Refactor inject

- .travis.yml
- Gemfile
- lib/polyamorous.rb
- lib/polyamorous/activerecord_3_and_4.0_ruby_1.9/join_association.rb
- lib/polyamorous/activerecord_3_and_4.0_ruby_1.9/join_dependency.rb
- lib/polyamorous/activerecord_4.1_ruby_1.9/join_association.rb
- lib/polyamorous/activerecord_4.1_ruby_1.9/join_dependency.rb
- lib/polyamorous/activerecord_4.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_4.1_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_4.1_ruby_2/make_polyamorous_inner_joins.rb
- lib/polyamorous/activerecord_4.2_ruby_1.9/join_association.rb
- lib/polyamorous/activerecord_4.2_ruby_1.9/join_dependency.rb
- lib/polyamorous/activerecord_4.2_ruby_2/join_association.rb
- lib/polyamorous/activerecord_4.2_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_5.0_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.0_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_5.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.1_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_5.2.0_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.2.0_ruby_2/join_dependency.rb
- lib/polyamorous/join.rb
- lib/polyamorous/swapping_reflection_class.rb
- lib/polyamorous/tree_node.rb
- ransack.gemspec
- spec/helpers/polyamorous_helper.rb
- spec/ransack/join_association_spec.rb
- spec/ransack/join_dependency_spec.rb
- spec/ransack/join_spec.rb
- spec/spec_helper.rb
As it is in the readme, the next major release should absorb polyamorous. 
/cc @seanfcarroll
> absorb polyamorous

- README.md
Per https://github.com/activerecord-hackery/ransack/issues/641, `*_present` is only compatible with string-like columns.
> Docs: Note limitation of the *_present predicate

- CHANGELOG.md
- README.md
- lib/ransack/adapters/active_record/base.rb
- lib/ransack/context.rb
- lib/ransack/search.rb
- spec/ransack/adapters/active_record/base_spec.rb
Currently Ransack documentation suggests you implement your own sanitization if you need the ability to pass truth-y values to a scope (1,0,t,f,etc.).  I have provided an add one to allow one to list scopes which should not be sanitized, and to continue using the existing mechanism for all other scopes.
This is particularly handy if you are passing form inputs into a scope.  (i.e. Power Search which searches across multiple fields)
> Add feature to allow selectively skipping scope argument sanitization.

- .travis.yml
- Gemfile
- lib/polyamorous.rb
- lib/polyamorous/activerecord_5.2.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.2.1_ruby_2/join_dependency.rb
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/constants.rb
- spec/helpers/polyamorous_helper.rb
- spec/ransack/adapters/active_record/base_spec.rb
Management of alias tracker has changed in https://github.com/rails/rails/commit/50036e673b3b6ff41476814b212b55fabac3a638.
So fixed accordingly with it.
> Add support for Rails 5.2.1

- .travis.yml
Ref: https://weblog.rubyonrails.org/2018/8/7/Rails-5-2-1-has-been-released/
> Test against Rails 5.2.1

- lib/polyamorous/activerecord_5.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.1_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_5.2.0_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.2.0_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_5.2.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_5.2.1_ruby_2/join_dependency.rb
- spec/ransack/join_association_spec.rb
- spec/ransack/join_dependency_spec.rb
`{find,build}_join_association_respecting_polymorphism` are no longer
used since existed them for Active Record 3.2 and 4.0.
> Remove internal methods which are no longer used

- CHANGELOG.md
- lib/ransack/adapters/active_record/context.rb
- spec/ransack/search_spec.rb
Added spec to #951, closes #947
> Don't return association if table is nil

- lib/polyamorous.rb
- lib/ransack/adapters/active_record/context.rb
* Remove unused constant aliases for `ActiveRecord::Associations::ClassMethods::*`
`ActiveRecord::Associations::ClassMethods::*` had already been moved to
`ActiveRecord::Associations::*` since Rails 3.1.
See rails/rails@b171b9e
* Remove unused constant aliases for `Arel::{InnerJoin,OuterJoin}`
`Arel::Nodes::{InnerJoin,OuterJoin}` exists since Arel 2.2 still today.
https://github.com/rails/arel/blame/v9.0.0/lib/arel/nodes/inner_join.rb
https://github.com/rails/arel/blame/v9.0.0/lib/arel/nodes/outer_join.rb
* Remove useless constant alias for `JoinDependency`
Originally it looks like for using shorter name in this file since
`ActiveRecord::Associations::ClassMethods::JoinDependency` was too long.
I think we can just use `Polyamorous::JoinDependency` existent alias.
* Remove unused constant …
> Remove unused/useless constant aliases

- CHANGELOG.md
- README.md
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/visitor.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
For when we want to sort by something complex such as the result of a SQL function.
**Credit**: This solution was borrowed from [this gist](https://gist.github.com/laserlemon/e5ce4e0d8bac63f4aa6835605ce3ec21).
> Add support for sorting by scopes

- lib/ransack/helpers/form_helper.rb
Currently in Rails 6.0.0.beta1 it dies with error:
`ActionController::UnfilteredParameters: unable to convert unpermitted parameters to hash`
This small fix allows it to work correctly
> Support Rails 6 in #sort_link helper

- CHANGELOG.md
- README.md
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/visitor.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
For when we want to sort by something complex such as the result of a SQL function.
Backport of bdd1c245.
reference https://github.com/activerecord-hackery/ransack/pull/973#issuecomment-459722305
> [1.8] Backport support for sorting by scopes

- lib/ransack/locale/az.yml
Corrects the wrong key in translations ```az``` instead of ```tr```
> correct azerbaijani translations

- lib/ransack/adapters/active_record/context.rb
- spec/ransack/search_spec.rb
Since the structure of Node returned by ActiveReocrd changed from 54de9b1, the spec execution failed.
refs: https://github.com/rails/rails/commit/54de9b1e4f5823bf22001be60efcb996ce6d260b
> Fix failing specs on local machine [fix #1023]

- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/predicate_spec.rb
Query with predicates defined with 'not_in' arel predicate results with an error "TypeError: can't quote Array"
activerecord-5.2.2/lib/active_record/connection_adapters/abstract/quoting.rb:179:in `_quote'
> Fix custom predicates with 'not_in' arel predicate

- README.md
I found mistake in readme for `ransackable_scopes`. If i set private_class_method ransackable_scopes doesnt work and i get error `NoMethodError (undefined method `ransackable_scopes' for #<Skill::ActiveRecord_Relation:0x0000563b3bc7d860>)`
> Fix readme for ransackable scopes

- lib/ransack/adapters/active_record/ransack/constants.rb
- spec/ransack/predicate_spec.rb
ransack is currently escaping period characters in mysql2. This is not correct and makes it impossible to search for things with periods in it (like email addresses).  In my limited experience with Postgres I believe it's correct to escape it there -- my patch splits the Postgres vs Mysql2 logic so the escaping for Postgres is left unchanged.
```
irb(main):001:0> unescaped = "je_rry.walsh|h%"
irb(main):002:0>          unescaped.to_s.gsub(/([\\%_.])/, '\\\\\\1')
=> "je\\_rry\\.walsh|h\\%"
irb(main):003:0>          unescaped.to_s.gsub(/([\\%_])/, '\\\\\\1')                                                                                                              
=> "je\\_rry.walsh|h\\%"
```
Only % and _ should be escaped since these are the only pattern characters supported in mysql: …
> Don't escape period characters with wildcard searches in mysql2

- .travis.yml
- Gemfile
- README.md
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/constants.rb
- polyamorous/lib/polyamorous.rb
- polyamorous/lib/polyamorous/activerecord_6.0_ruby_2/join_association.rb
- polyamorous/lib/polyamorous/activerecord_6.0_ruby_2/join_dependency.rb
- polyamorous/lib/polyamorous/activerecord_6.0_ruby_2/reflection.rb
- ransack.gemspec
- spec/helpers/polyamorous_helper.rb
- spec/ransack/join_dependency_spec.rb
Closes #1021
Rails 6 is still under development and breaking changes are happening even in RC versions.  Just a month a go this pull request https://github.com/rails/rails/pull/36120 was merged after `6.0.0.rc1` was released.
This branch is compatible with latest `6-0-stable` branch , which means it will _probably_ be compatible with Rails `6.0.0.rc2` when its released if no future changes are made.
CI will pass if https://github.com/activerecord-hackery/ransack/issues/1024 is merged.
> Support for Rails 6

- ransack.gemspec
The RubyGems property rubyforge_project is removed without a replacement.
> gemspec: Drop EOL property rubyforge_project

- README.md
Rails 6.0.0.rc2 https://rubygems.org/gems/rails/versions/6.0.0.rc2 has been released.
Rails 6.0.0.rc2 includes https://github.com/rails/rails/commit/f8c4e29026e then I think Ransack master branch works with Rails 6.0.0.rc2.
This pull request follows up https://github.com/activerecord-hackery/ransack/commit/94ab1db70ce6030a26bc0e407bddd8ac7fbbf977 to update `Rails 6 Support`.
> Ransack master branch supports Rails 6.0.0.rc2

- README.md
Ransack 2.3.0 seems supporting Rails 6.0. So I think this note needless now.
> Remove note about Rails 6.0 support [ci skip]

- .travis.yml
- Gemfile
- ransack.gemspec
Hei! I initially prepared this patch to fix not being able to point to ransack's master branch from my Gemfile unless I define an `ENV["RAILS"]` environment variable.
That seems fixed by #1058, but in any case, this implements a set of better practices when managing your gemspec.
In general, development dependencies fit better in your Gemfile, because they are only considered for development, an never affect end users like it happened here. Also, gemspecs don't have the feature of "conditional dependencies", which was probably the intention for the `sqlite3` dependency here.
> Refactor gemspec

- .travis.yml
Just two small improvements:
* We don't need to setup a DB if we're not testing against it.
* We don't need `sudo: false`, because TravisCI [deprecated it](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
> Improve CI setup

- Gemfile
There were two problems:
* An absolute path is not a something `Gem::VERSION` understands, so in
the "path case", read the `RAILS_VERSION` file from the Rails clone and
use that.
* In the "path case" there were some missing dependencies. Add them to
the Gemfile.
> Fix running tests against a Rails clone

- CHANGELOG.md
- Gemfile
- README.md
- ransack.gemspec
I want to create a PR to fix some issues with (unreleased) ruby 2.7, but I want to use String#+@, which is only available since ruby 2.3.
I can create a different patch (backwards compatible with all currently supported rubies) using `String#dup`, but since ruby 1.9, 2.0, 2.1 and 2.2 reached their end of life a while ago, I figure we could drop support for those.
> Drop old rubies support

- spec/support/schema.rb
Provide a little more flexibility when configuring the test DB, so developers with custom configuration don't need to edit the source files.
> Allow configuring test DB connection

- README.md
The readme should make clear, that the ransackable_scopes_skip_sanitize_args method is a model class method, not an instance method.
> Improves ransackable_scopes_skip_sanitize_args doc

- CHANGELOG.md
- lib/ransack/version.rb
- polyamorous/lib/polyamorous/version.rb
Bump to 2.3.2 as both Ransack and Polyamorous need to be bumped at the same time and a Rubygem cannot be republished.
https://github.com/activerecord-hackery/ransack/issues/1094
> Bump 2.3.2

- ransack.gemspec
This gem also includes the polyamorous gem (for now). We must not include its code inside the ransacks gem package.
Closes #1102
> Only include necessary files in gem package

- CHANGELOG.md
- CONTRIBUTING.md
- Gemfile
- lib/ransack/adapters/active_record/context.rb
- spec/ransack/adapters/active_record/context_spec.rb
- spec/ransack/search_spec.rb
- spec/support/schema.rb
re #1111 
* Fixed CONTRIBUTING doc
* Added failing spec
* RAILS=v5.2.3 bundle exec rspec spec/ransack/adapters/active_record/context_spec.rb:83 passes
* RAILS=v5.2.4 bundle exec rspec spec/ransack/adapters/active_record/context_spec.rb:83 fails (likewise untagged v5.2.4.2/5-2-stable)
* RAILS=v6.0.2.1 bundle exec rspec spec/ransack/adapters/active_record/context_spec.rb:83 passes
* proposed fix (assuming CI runs on initial commits to show history of failure before success
* additional bug spec for not_eq additional conditions, pending because I don't know how to fix that one
> Test/Fix for subquery in Rails 5.2.4 

- .travis.yml
- Include tests against Rails 6.0.1 and 6.0.2
- Remove 'allow failure' section from CI
- Thanks to @gregmolnar for [most of the code](https://github.com/activerecord-hackery/ransack/pull/1100)
> Additional Rails vers in CI

- lib/ransack/translate.rb
In Ruby 2.7 passing the last argument as an options hash if the receiver uses keyword arguments is no longer allowed and throws a warning.
This PR applies the recommended fix of adding `**` to covert the options hash into the correct keyword arg format.
There may be more deprecation warnings to fix in other parts of the codebase but these were the ones that jumped out to me right away.
> Fix Ruby 2.7 deprecation warnings

- lib/polyamorous/activerecord_5.2_ruby_2/reflection.rb
- spec/ransack/search_spec.rb
* Polymorphic joins have been missing a critical join constraint that
is responsible for only returning polymorphic records of the specified
type.
* Override ActiveRecord::Reflection::AbstractReflection#join_scope to
add this constraint if the reflection is polymorphic.
Polymorphic searching has been **broken in Ransack** since https://github.com/rails/rails/commit/49bcb008cbaf0fa2db727ae58e7e27015a7ae02c.
This PR closes https://github.com/activerecord-hackery/ransack/issues/1039, closes https://github.com/activerecord-hackery/ransack/issues/1120, and closes https://github.com/activerecord-hackery/ransack/pull/1077.
This bug has been a source of great frustration for our organization, and presumably many users of this library are completely unaware of the incorrect queries being formed by …
> Fixes polymorphic joins.

- Gemfile
- spec/ransack/adapters/active_record/base_spec.rb
This is a prerequisite for being able to run specs against Rails 6.1, since previous faker versions were holding down the i18n dependency with a requirement incompatible with newest Rails.
> Run specs using a newer faker

- .travis.yml
We only care about the latest patch level release for each major Rails.
> Remove redundant CI entries

- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
I've been bisecting specs against Rails 6.1 and the first set of failures I get is:
```
Failures:
1) Ransack::Adapters::ActiveRecord::Base#ransacker searching on an `in` predicate with a ransacker should function correctly when passing an array of ids
Failure/Error: expect(s.result.count).to be > 0
expected: > 0
got:   0
2) Ransack::Adapters::ActiveRecord::Base#ransacker searching on an `in` predicate with a ransacker should function correctly when passing an array of strings
Failure/Error: expect(s.result.count).to be > 0
TypeError:
can't quote Array
3) Ransack::Predicate defining custom predicates with 'not_in' arel predicate generates a value IS NOT NULL query
Failure/Error: expect(@s.result.to_sql).to match /#{field} NOT IN \('a', 'b'\)/
TypeError:
can't quote Array
Finished in 1.54 …
```
> Adapt to quoting change in Rails

- README.md
I think this is a typo, should be `ILIKE`, since it's case insensitive.
> Typo in docs

- lib/ransack/nodes/grouping.rb
This change makes Ransack compatible with shopify/symbol-fstring since `Symbol#to_s` will return a frozen string literal.
> Use unfrozen version of symbol to string

- .github/workflows/test.yml
This pull request enables CI against Rails 6.1.0.rc2
Rails 6.1.0.c2 has been released on Dec 1st.
https://weblog.rubyonrails.org/2020/12/1/Rails-6-1-rc2-release/
> CI against Rails 6.1.0.rc2

- .github/SECURITY.md
- README.md
I found that Github provides this file that integrates better with them.
> Move security contact information to SECURITY.md

- CHANGELOG.md
- README.md
- lib/ransack/adapters/active_record/base.rb
- lib/ransack/search.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/search_spec.rb
**Use case:** We use Ransack for both public-facing search pages and internal purposes such as targeting bulk email deliveries. In the context of public-facing search, we'd like to be lenient with unknown/invalid search params. However, in the context of targeting bulk emails, this seems dangerous - a broken query could potentially go out to many more recipients than intended.
Thus, we'd like to be able to trigger the `ignore_unknown_conditions` config option on a case-by-case basis. (Previously requested in https://github.com/activerecord-hackery/ransack/issues/535)
I've drafted what feels like a clean implementation, although here are some other options I considered:
```ruby
Person.ransack(unknown_attr_eq: "Ernie").validate!.result
Person.ransack(unknown_attr_eq: "Ernie", …
```
> Add ransack! method which raises error if passed unknown condition

- README.md
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/configuration.rb
- spec/ransack/configuration_spec.rb
- spec/ransack/search_spec.rb
Close #1125
Related to https://github.com/activerecord-hackery/ransack/issues/443#issuecomment-551390658
https://www.postgresql.org/docs/13/queries-order.html
> Add ability to config PostgreSQL ORDER BY ... NULLS FIRST or NULLS LAST

- .github/workflows/test.yml
This pull request enables CI against Rails 6.1.0.
Rails 6.1.0 has been released on Dec 9, 2020.
https://weblog.rubyonrails.org/2020/12/9/Rails-6-1-0-release/
> CI against Rails 6.1.0

- lib/ransack/adapters/active_record/context.rb
- lib/ransack/constants.rb
Rails 6.1.0 has been released already, Ransack does not have to consider 6.1.0.alpha version anymore.
> Replace constant `RAILS_6_1_ALPHA` with `RAILS_6_1`

- .github/workflows/rubocop.yml
- .github/workflows/test.yml
This pull request runs CI against Ruby 3.0.0.
Rails 6.0.3 or higher is required to support Ruby 3 keyword arguments behavior then excluded the matrix between Ruby 3.0.0 and Rails 5.2.x.
* Rails 6.0.3 has been released!
https://weblog.rubyonrails.org/2020/5/6/Rails-6-0-3-has-been-released/
> This version fixes warnings when used with Ruby 2.7.
* Ruby 3.0.0 Released
https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
> Keyword arguments are separated from other arguments.
> CI against Ruby 3.0.0

- CHANGELOG.md
- ransack.gemspec
README already mentions that `Ransack is supported for Rails 6.1, 6.0,
5.2 on Ruby 2.6.6 and later.` by https://github.com/activerecord-hackery/ransack/commit/d50885772cfa9c2534c06f7edb0eb4141f2e1a4a
I'd like to get some feed back from maintainers since #1070 just dropped Ruby 2.2 or older versions of Ruby.
> Drop Ruby 2.5 or older versions of Ruby

- .rubocop.yml
- Gemfile
- lib/ransack.rb
- spec/spec_helper.rb
This pull request bumps RuboCop version by removing version limitation because Ransack supports Ruby 2.6 or higher.
Also enabled `Style/RedundantFileExtensionInRequire` cop which is available since RuboCop 0.88.0.
> Bump RuboCop

- Gemfile
- spec/console.rb
- spec/spec_helper.rb
This pull request bumps Faker version to 2 to use keyword arguments
- Change Faker arguments by RuboCop Faker
```ruby
$ gem install rubocop-faker
$ rubocop --require rubocop-faker --only Faker/DeprecatedArguments -a
Inspecting 70 files
....................................................C...............C.
Offenses:
spec/console.rb:17:33: C: [Corrected] Faker/DeprecatedArguments: Passing 3 with the 1st argument of Faker::Lorem.words is deprecated. Use keyword argument like Faker::Lorem.words(number: 3) instead.
tag_name { Faker::Lorem.words(3).join(' ') }
^
spec/console.rb:18:33: C: [Corrected] Faker/DeprecatedArguments: Passing 7 with the 1st argument of Faker::Lorem.words is deprecated. Use keyword argument like Faker::Lorem.words(number: 7) instead.
note     { …
```
> Bump Faker 2 to use keyword arguments

- .github/workflows/test.yml
This pull request runs CI against Rails 6.1.1.
https://github.com/rails/rails/releases/tag/v6.1.1
> CI against Rails 6.1.1

- CHANGELOG.md
* Add section for `2.4.1` release
* Remove empty entry
> Fix CHANGELOG [ci skip]

- .github/workflows/test.yml
- CONTRIBUTING.md
- bug_report_templates/test-ransack-scope-and-column-same-name.rb
- bug_report_templates/test-ransacker-arel-present-predicate.rb
This pull request moves bug report templates into ransack repository and run templates at CI.
> Move bug report templates into ransack repository and run templates at CI

- .github/workflows/cronjob.yml
- Gemfile
- lib/polyamorous/activerecord_6.2_ruby_2/join_association.rb
- lib/polyamorous/activerecord_6.2_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_6.2_ruby_2/reflection.rb
This pull request allows Ransack to be tested with Rails master branch aka 6.2.0.alpha.
Let me explain some background for this change.
Ransack (polyamorous) depends on some Rails internal APIs and Rails internal APIs change without deprecation warnings. In the long term, Ransack (polyamorous) may not depend on these internal API, but as of now, what we can do is run CI against Rails master branch so that we will able to know which commits 'break' Ransack behavior.
> Allow Ransack to be tested with Rails main branch

- spec/ransack/adapters/active_record/base_spec.rb
This commit addresses this RSpec warning below:
```ruby
$ bundle exec rspec spec/ransack/adapters/active_record/base_spec.rb:126
Run options: include {:locations=>{"./spec/ransack/adapters/active_record/base_spec.rb"=>[126]}}
====================================================================================
Running Ransack specs with SQLite, Active Record 6.0.3.4, Arel 10.0.0 and Ruby 2.7.2
====================================================================================
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. …
```
> Address RSpec warning by specifying as ArgumentError

- CONTRIBUTING.md
According to this blog post, GitHub Actions now supports skip pull request.
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
This commit partially restores the CONTRIBUTING.md changed by #1180.
> [skip ci] GitHub Actions can skip CI now

- lib/ransack/adapters/active_record/context.rb
- spec/ransack/search_spec.rb
This PR fixing issue with Rails 6.1 and explicit whitelisting potentially dangerous SQL.
More information here:
https://api.rubyonrails.org/classes/ActiveRecord/UnknownAttributeReference.html
> Fix for ActiveRecord::UnknownAttributeReference in ransack

- lib/polyamorous.rb
By providing `polyamorous.rb` in the `lib` folder, projects that
previously depended directly on `polyamorous` can just switch the
dependency to `ransack` without changing their calls to `require`.
> Make gem compatible with old polyamorous require

- .github/workflows/cronjob.yml
This commit addresses these errors at cronjob.
https://github.com/activerecord-hackery/ransack/runs/1966021652?check_suite_focus=true
```
activesupport-7.0.0.alpha requires ruby version >= 2.7.0, which is incompatible
with the current version, ruby 2.6.6p146
Error: Process completed with exit code 5.
```
Refer
https://github.com/rails/rails/commit/6487836af8f50648a9b30ce61864c827132e5592
> Drop Ruby 2.6 from cronjob as Rails 7 requires Ruby 2.7+

- .github/workflows/test.yml
- "Rails 6.1.3 has been released"
https://weblog.rubyonrails.org/2021/2/17/Rails-6-1-3-has-been-released/
> CI against Rails 6.1.3

- README.md
Describe how to extend Ransack to perform a case insensitive search on PostgreSQL. 
Closes https://github.com/activerecord-hackery/ransack/issues/1201
> How to do case insensitive searches

- README.md
- lib/ransack/configuration.rb
- lib/ransack/search.rb
- spec/ransack/configuration_spec.rb
- spec/ransack/search_spec.rb
Follow up to discussion in #1198
> Add the ability to disable whitespace stripping for string searches

- lib/ransack/translate.rb
At the moment it's possible to pass a default translation (or translation key) to the Ransack::Translate.attribute method, however it is never actually accessed given the existing fallback using interpolated attribute/predicate names. Those interpolated strings are either "%{attributes}" or "%{attributes} %{predicate}", which never return nil. Any value passed to options[:default] is added to the end of the defaults array (after those never-nil interpolated strings), and as a result the default that is specifically supplied by the user of the gem is never actually accessed or output. This pull request is aimed at resolving that (ever-so-slight) bug
> Fix :default option in Translate.attribute method

- .github/workflows/test.yml
- Rails 6.1.4 has been released
https://weblog.rubyonrails.org/2021/6/24/Rails-6-1-4-has-been-released/
> Bump Rails version to 6.1.4

- .github/workflows/cronjob.yml
- .github/workflows/rubocop.yml
- .github/workflows/test.yml
* Ruby 3.0.1 Released
https://www.ruby-lang.org/en/news/2021/04/05/ruby-3-0-1-released/
* Ruby 2.7.3 Released
https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-7-3-released/
> Bump Ruby versions to 3.0.1 and 2.7.3

- spec/ransack/adapters/active_record/base_spec.rb
This pull request fixes #1231 
Follow up rails/rails#42440
Fix #1231
This pull request addresses the following failure. 
- Note:`RAILS` path is the directory where Rails main branch checked out, MYSQL_USERNAME and MYSQL_PASSWORD depend on the configuration.
```ruby
$ RAILS=/home/yahonda/src/github.com/rails/rails DB=mysql MYSQL_USERNAME=root MYSQL_PASSWORD=root bundle exec rspec
========================================================================================
Running Ransack specs with Mysql2, Active Record 7.0.0.alpha, Arel 10.0.0 and Ruby 3.0.1
========================================================================================
............................................................DEPRECATION WARNING: ActiveRecord::Base.default_timezone= is deprecated and will be …
```
> Support Rails untyped bound values change for MySQL

- spec/ransack/adapters/active_record/base_spec.rb
This commit addresses the following failure.
```ruby
$ bundle exec rspec ./spec/ransack/adapters/active_record/base_spec.rb:316
Run options: include {:locations=>{"./spec/ransack/adapters/active_record/base_spec.rb"=>[316]}}
========================================================================================
Running Ransack specs with SQLite, Active Record 7.0.0.alpha, Arel 10.0.0 and Ruby 3.0.1
========================================================================================
F
Failures:
1) Ransack::Adapters::ActiveRecord::Base#ransacker should function correctly with a multi-parameter attribute
Failure/Error: ::ActiveRecord::Base.default_timezone = :utc
NoMethodError:
undefined method `default_timezone=' for ActiveRecord::Base:Class
Did you mean?  default_timezone
Finished in …
```
> Rails 7 `default_timezone` is a module instance variable

- .github/workflows/test.yml
- Rails 6.0.4 has been released
https://weblog.rubyonrails.org/2021/6/15/Rails-6-0-4-has-been-released/
> Bump Rails version to 6.0.4

- README.md
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/configuration.rb
- spec/ransack/search_spec.rb
Current sort options are strangely determined by ASC, DESC order. This fix allows to circumvent that, without breaking backwards compatibility.
> allow ransack to treat nulls as always first or last

- README.md
- lib/ransack/nodes/sort.rb
- spec/ransack/search_spec.rb
Duplicates #766 and #1084 but this one have tests. All credit should be given to the PR authors.
> Enable sort using alias

- .github/workflows/cronjob.yml
- .github/workflows/test.yml
* Ruby 3.0.2 Released
https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/
* Ruby 2.7.4 Released
https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/
* Ruby 2.6.8 Released
https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-6-8-released/
> Bump Ruby versions to 3.0.2, 2.7.4 and 2.6.8

- spec/ransack/search_spec.rb
This commit partially reverts #1171
Rails 6.0.4 has been released including the commit below.
https://github.com/rails/rails/commit/f9ba52477ca288e7effa5f6794ae3df3f4e982bc
> No need to skip the test because Rails 6.0.4 is out

- CHANGELOG.md
- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/nodes/condition_spec.rb
- spec/support/schema.rb
Have casted array predicates type checked to Arel::Nodes::Casted fixing non-casted array predicates.
> Fixing non-casted array predicates. Resolves issue #1245

- README.md
See background: https://github.com/activerecord-hackery/squeel/pull/428
> Squeel should no longer be recommended

- README.md
It is not an actual issue with ransack itself, but I'm finding calling `to_a.uniq` on paginated active record collection misleading, it also can give incoherent results. 
if provided README example `@q.result.includes(:articles).page(params[:page]` returns a collection with duplicated results, then calling `to_a.uniq` will reduce a number of returned records, that means that the page offset will no longer be correct. 
**Steps to reproduce:**
1. Create two Person records in database
2. Create 10 articles containing word "dog" and assign it to the first Person
3. Create 1 article containing word "dog" and assign it to the second Person
4. Perform a paginated search for all Person records that wrote an article containing "dog" word, you would like to fetch first 10 records of 1st page. …
> Remove part of the README that might lead to incorrect results

- .github/workflows/test.yml
This pull request adds CI against Rails 7.0.0 which has been released on Dec 15, 2021.
https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision
Rails 7 requires Ruby 2.7.0 or higher.  Then excluded matrix for Ruby 2.6.
Refer: https://github.com/rails/rails/blob/984c3ef2775781d47efa9f541ce570daa2434a80/rails.gemspec#L12
> CI against Rails 7.0.0

- lib/polyamorous/activerecord_5.2_ruby_2/join_association.rb
- lib/polyamorous/activerecord_6.1_ruby_2/join_association.rb
- spec/polyamorous/activerecord_compatibility_spec.rb
- spec/polyamorous/join_association_spec.rb
- spec/support/schema.rb
Our polyamorous monkeypatches were doing too much. Removing our custom equality and letting ActiveRecord figure it out seems to do the trick and fix this.
On some Rails & DB adapters this seems to break a polyamorous spec. However, this spec just tests an implementation detail but it's unclear whether the spec breaking has any actual bad side effect in real like, so I removed it.
Fixes #1271.
> Fix issue with self joins and includes

- README.md
- lib/ransack/adapters/active_record/base.rb
- spec/ransack/adapters/active_record/base_spec.rb
`#search` is deprecated in v2.1.1 and it scheduled to remove the method in v2.3.
https://github.com/activerecord-hackery/ransack/pull/975
But the method still exists in v2.3.2. So let's remove the method.
If we removed the method, users can remove the patch for `search` (`ActiveRecord::Base.class_eval('remove_method :search'`).
> Remove deprecated `#search` method

- CHANGELOG.md
- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
In the end I decided to make this fix backwards compatible.
I will deprecate passing two different option hashes in a separate PR.
Fixes #1277.
> Fix `:class` option to `sort_link` when no additional parameters are given

- README.md
As per https://github.com/rubygems/rubygems/pull/5337, we can simplify the steps of adding a gem.
> Use `bundle add` in README installation instructions

- CHANGELOG.md
- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
Pass a single options hash instead.
> Deprecate passing two trailing hashes to `sort_link`

- CHANGELOG.md
- README.md
While working on #1288 and #1289, I noticed that the signature of this method is quite convoluted.
I tried to clarify it here.
> Improve `sort_link` documentation

- docs/docs/going-further/wiki-contributors.md
Extract a list of all contributors from the old Ransack wiki.
Part of https://github.com/activerecord-hackery/ransack/issues/1295
> Add list of wiki contributors

- CHANGELOG.md
- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
Fixes https://github.com/activerecord-hackery/ransack/pull/1289#issuecomment-1084225840.
@dmitrue Can you verify whether this fixes your issue?
> Don't pass `data` attribute appended to query params

- docs/docs/going-further/acts-as-taggable-on.md
- docs/docs/going-further/polymorphic-search.md
Add missing content from Wiki
- Acts as taggable on
- Polymorphic searches
> Improve documentation

- .github/workflows/test.yml
This pull request updates CI as follows.
* Update Rails version to the latest Rails 7.0.2, 6.1.5
* Remove CI against 6-0-stable branch because Rails 6.0.z only accepts severe security issues
* Add Ruby 3.1.1, removed Ruby 2.6.7 from CI
> Tidy up CI

- docs/docs/going-further/acts-as-taggable-on.md
> Ransack search with ActsAsTaggableOn

- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
> Exclude "host" from params sent to url generator

- .github/workflows/test.yml
This pull request bumps Rails and Ruby versions.
- Rails 7.0.3, 6.1.6, 6.0.5, and 5.2.8 have been released!
https://rubyonrails.org/2022/5/9/Rails-7-0-3-6-1-6-6-0-5-and-5-2-8-have-been-released
- Ruby 3.1.2 Released
https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/
- Ruby 3.0.4 Released
https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/
- Ruby 2.7.6 Released
https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
> Bump Rails and Ruby versions

- docs/docs/getting-started/simple-mode.md
- docs/docs/getting-started/sorting.md
- docs/docs/going-further/acts-as-taggable-on.md
- docs/docs/going-further/exporting-to-csv.md
- docs/docs/intro.md
- docs/docusaurus.config.js
Added support `ruby` and `erb` syntax to the Prism settings. Changed `rb` key to `ruby` in code blocks. ~~Some refactor in README.~~
Fixed #1307
> Added support of ruby and erb syntax highlightings

- README.md
The "Contributing Guide" links doesn't work in README. Fixed links, refactor code-blocks with ruby.
> Fixed contributing urls in readme.

- lib/ransack/nodes/value.rb
- spec/ransack/nodes/value_spec.rb
Before Rails 7, PostgreSQL's timestamptz columns were handled as `datetime`, but now `type` returns `:timestamptz`:
```
irb(main):181:0> User.columns_hash['created_at'].type
=> :timestamptz
```
I tested this PR's change in my production app, it's working fine, but let me know if this is not the correct/complete fix for the issue.
> Cast PostgreSQL's timestamptz columns to time

- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
> Add a local search plugin to documentation site

- docs/docs/going-further/searching-postgres.md
The current link points to a github wiki that apparently is not there anymore.
> Fix broken documentation link

- docs/package.json
- docs/yarn.lock
We have a couple of security alerts about docusaurus dependencies. I don't think these vulnerabilities really affect a framework like docusaurus, but there are fixes out there, so these PR upgrades the dependencies to get rid of the alerts.
> Bump docusaurus

- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- spec/ransack/predicate_spec.rb
Fixes https://github.com/activerecord-hackery/ransack/issues/1337
> Ignore ActiveModel::RangeError in Ransack conditions

- lib/ransack/adapters.rb
Closes https://github.com/activerecord-hackery/ransack/issues/1344
> Remove dead MongoDB code

- docs/docs/getting-started/simple-mode.md
In my opinion, docs should warn about not authorizing by default. This can cause serious problems when filtering the user model for example. One could easily extract email addresses, password hashes or other sensitive information.
> Add warning about necessary authorization

- .rubocop.yml
- Gemfile
- lib/ransack.rb
- lib/ransack/configuration.rb
- lib/ransack/helpers/form_builder.rb
- lib/ransack/nodes/attribute.rb
- lib/ransack/nodes/condition.rb
- lib/ransack/nodes/grouping.rb
- lib/ransack/nodes/node.rb
- lib/ransack/nodes/value.rb
- lib/ransack/ransacker.rb
- lib/ransack/search.rb
- lib/ransack/translate.rb
- spec/ransack/configuration_spec.rb
- spec/ransack/helpers/form_builder_spec.rb
- spec/ransack/helpers/form_helper_spec.rb
- spec/ransack/translate_spec.rb
Extracted from https://github.com/activerecord-hackery/ransack/pull/1348
> Code quality improvements

- lib/polyamorous.rb
Extracted from https://github.com/activerecord-hackery/ransack/pull/1348
> I think we can hold it until you can have a look. Breaking require "polyamorous" could be considered a breaking change so I'd ship it with 4.0.0 too.
Should we make the next release 4.0.0 ? @deivid-rodriguez ?
> Remove Polyamorous entrypoint

- docs/package.json
- docs/yarn.lock
* Upgrades docusaurus to 2.2.0, mainly to silence some security alerts.
* Also pins trim and got to know fixed versions. This overrides the actual constraints set on them, but I don't think they are actually used by docusaurus, so it should be ok.
> Upgrade some documentation dependencies

- README.md
The gemspec states that the minimum required ruby version is 2.7 and the minimum required AR/AS versions are 6.1.5
This commit fixes the readme accordingly
[ci skip]
> Fix required Ruby and Rails version

- lib/ransack/helpers/form_helper.rb
- spec/ransack/helpers/form_helper_spec.rb
Currently, it is possible to change the host simply by passing a host through params. This way, visiting ```example.com/people?host=some_other_domain``` would then have sort_links with ```http://some_other_domain/people..```.
> Prevent changing host through params

- lib/ransack/configuration.rb
- lib/ransack/predicate.rb
- spec/ransack/nodes/condition_spec.rb
Currently predicates are required, otherwise the conditions are ignored or they will raise an error.
When using Ransack for filtering in json requests, it would be nice to allow an empty predicate to equal to true.
So instead of having to explicitly pass '*_eq':
{
product_id_eq: 'product-1',
type_eq:       'admin'
}
we can do the following:
{
product_id: 'product-1',
type:       'admin'
}
This adds a `:default_predicate` configuration option that will be used in case of a missing predicate.
I'm not sure anyone would use a different default, so maybe the config option should be something like: `:default_to_eq_predicate`.
> Add support for default predicates

- bug_report_templates/test-ransacker-arel-present-predicate.rb
- lib/ransack/adapters/active_record/base.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
> Require explict allowlisting of attributes and associations

- docs/docs/going-further/other-notes.md
Update link for "Why you Ruby class macros (might) suck (mine did)" blog post
> [skip ci] Update blog post link

- .github/workflows/test.yml
- lib/ransack/adapters/active_record/context.rb
Right now, Ransack fails to execute on Rails 7.1.0beta1 with the error below:
```
1) Ransack::Search#method_missing allows chaining to access nested conditions
Failure/Error: table        = attr.arel_attribute.relation.table_name
NoMethodError:
undefined method `table_name' for #<Arel::Table:...>
```
This is because the `table_name` method has been dropped as part of this commit https://github.com/rails/rails/commit/1d98bc563a8a7faf26238eaaa54a3257a95d644d, which has made Rails imcompatible with Ransack.
This PR adds a check for the existence of the `table_name` method to restore the compatibility.
> Fix builds for Rails 7.1.0

- docs/docs/getting-started/sorting.md
Closes #1419
Updates the sorting code examples to be vanilla and make it clear how to use sorting.
Easy code review in [this gist](https://gist.github.com/kinduff/e512fb88bdb1be1da8503c7373b6bbb0).
> Docs: Updates sorting example

- CONTRIBUTING.md
It will be caught by CI anyways and it gets out of date easily.
> Don't mention Ruby compatibility in contribution instructions

- lib/polyamorous/activerecord_6.1_ruby_2/join_dependency.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
I encountered the same issue as reported in #1217 (and possibly in a bunch of other issues as well[^1]).
It was correctly pointed out, that a change in ActiveRecord was responsible. https://github.com/rails/rails/commit/10b36e81a357f8d7fa3665630c4d41c057fe59d9 tried to fix a bug with eager loading that resulted from aliasing a joined table that was (then incorrectly) referenced in a WHERE clause.
The solution (as far as I understand it - I never had to look at that code before and cannot say I understand all of what is going on there) was to cache tables already joined and reuse those joins if possible.
The problem in #1217 is caused by ransack prepopulating table information *before* this deduplication code is run. So there is no way to detect that a JOIN clause with an alias, that would …
> Fix wrong table aliases (#1217)

- lib/ransack/context.rb
Currently `ransackable_scopes` allows both, and for some reason the rest expects %w only.
> Update context to support both %i and %w for ransachable_* methods

- lib/ransack.rb
Include the file `version.rb` to define the `Ransack::VERSION` const.
Ransack defines a `VERSION` const, but the `version.rb` file is not included in the requires list in the gem entry code.
> Include version const

- .github/workflows/test.yml
- Gemfile
- lib/polyamorous/activerecord/join_association_7_2.rb
- lib/polyamorous/polyamorous.rb
- lib/ransack/adapters/active_record/context.rb
> Make ransack work with Rails 7.2

- docs/docs/getting-started/simple-mode.md
- docs/docs/going-further/other-notes.md
Fixes #1426
Maybe also the cause of confusion in https://github.com/activerecord-hackery/ransack/issues/1519?
The ransack documentation states that by default all columns and associations are ransackable.  That is not true as of `v4.0` where more secure defaults were put in place.  This PR modifies the documentation to call out this change.
> Update docs for required allowlists in v4.0

- CHANGELOG.md
- docs/docs/going-further/other-notes.md
- lib/ransack/invalid_search_error.rb
- lib/ransack/nodes/condition.rb
- lib/ransack/search.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/nodes/condition_spec.rb
- spec/ransack/search_spec.rb
Currently, when Ransack encounters invalid search attributes (those not included in `ransackable_attributes`) while using `Model.ransack!()` it raises a generic `ArgumentError`. This makes it difficult to provide helpful feedback to an API consumer that their search params are incorrect.
This PR adds a custom exception type `Ransack::InvalidSearchError` and raises it instead of `ArgumentError` in cases where there are invalid attributes used in a search.
The solution in this PR should be perfectly backwards compatible. The new error inherits from ArgumentError, and the test cases assert this. 
Assume I have the following code in my controller
```ruby
def index
results = User.ransack!(frist_name_eq: 'John').result 
render json: to_json(result)
end
```
As a result this will return 5xx to …
> Raise Ransack::InvalidSearchError instead of ArgumentError on unknown conditions

- lib/polyamorous/polyamorous.rb
- lib/ransack.rb
- lib/ransack/helpers/form_builder.rb
- spec/spec_helper.rb
Fixes #1518 
In a typical Rails app, the Ransack gem gets loaded before ActiveRecord gets loaded.  [Rails recommends](https://guides.rubyonrails.org/configuring.html#avoid-loading-rails-frameworks) that gems avoid loading Rails frameworks when they themselves are loaded.  Ransack accomplishes that (as far as I can tell); however, Ransack initializes certain parts of its code within blocks like
```ruby
if defined?(::ActiveRecord)
...set up some stuff
end
```
If Ransack is loaded before `ActiveRecord` is loaded, those blocks of code are never reached.  I think these blocks of code should be wrapped with `ActiveSupport.on_load(:active_record)` instead of `if defined?(::ActiveRecord)`.  The blocks of code should run after `ActiveRecord` is loaded, which is what `on_load(:active_record)` is …
> Fix rails 7.2 loading

- .rubocop.yml
- Gemfile
- spec/ransack/helpers/form_helper_spec.rb
- spec/ransack/nodes/grouping_spec.rb
- spec/ransack/search_spec.rb
Extracted and extended from #1559.
> Add blank lines after last `let` in RSpec examples

- lib/ransack/nodes/value.rb
- spec/ransack/nodes/value_spec.rb
Ensure malformed or malicious user input doesn't crash the Rails page.
Previously, when a user submits a non-empty array, it would raise the exception:
```
NoMethodError: undefined method 'to_i' for an instance of Array
```
Fixes #1556
> Cast array input to integer node value as nil

- ransack.gemspec
This PR suggests addition of an explicit Changelog link to the rubygems ransack page.
> Add changelog_uri metadata to ransack.gemspec

- ransack.gemspec
Documented here: https://guides.rubygems.org/specification-reference/#metadata 
Useful for running https://github.com/MaximeD/gem_updater
I chose the releases page because `CHANGELOG.md` is missing the newest version, 4.1.1.
> Add changelog_uri to gemspec

- .gitignore
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/nodes/condition.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/adapters/active_record/context_spec.rb
- spec/ransack/nodes/condition_spec.rb
- spec/ransack/search_spec.rb
- spec/support/schema.rb
This PR addresses several issues with Ransack's handling of polymorphic associations and negative predicates:
1. **Polymorphic Association Support**: Added proper handling for polymorphic associations in correlated subqueries by correctly managing both foreign key and type columns.
2. **Negative Predicate Handling**: Fixed the behavior of negative predicates (`not_null`, `not_cont`, etc.) when used with associations:
- `not_null: true/false` now generates the correct IN/NOT IN queries
- `not_cont` now properly generates NOT IN queries with LIKE conditions
3. **Complex AND Conditions**: Improved extraction of correlated keys from complex AND conditions with multiple children.
4. **String Wildcard Handling**: Added proper quoting for string values containing wildcards (%) in LIKE …
> Fix nested conditions, polymorphic associations handling
