- CHANGELOG.md
Updated the changelog to include PR #486
> Update changelog with #486 [skip ci]

- README.md
- lib/ransack/helpers/form_helper.rb
sort_link add hide_indicator options, default: false
> sort_link add hide_indicator options

- CHANGELOG.md
- spec/support/schema.rb
Follow-up to #513 
Specify #513 PR in changelog
> Update CHANGELOG [ci skip]

- CHANGELOG.md
* Updated the CHANGELOG.md to include #562
> Update CHANGELOG with #562 [ci skip]

- CHANGELOG.md
- README.md
> Update documentation with Mongoid 5 support.

- .travis.yml
> Run tests with latest stable versions

- README.md
1. headers, add spaces after the number sign #.
2. links, must be on the same line.
> [skip ci] Improve docs

- README.md
> fix badge link

- README.md
Should be enough information to mark #453 as closed 😄
> Add a note about DISTINCT and PostgreSQL json columns.

- CHANGELOG.md
A bit faster to read this way, I think.
> Condense entries re: new locale files

- lib/ransack/adapters/active_record/context.rb
- lib/ransack/constants.rb
Fix #807 and all specs become green in rails master.
refs
- https://github.com/rails/rails/pull/28267
- https://github.com/rails/rails/pull/27851
> No need pass some arugments to JoinAssociation#join_constraints in Rails 5.1

- .gitignore
- Gemfile
- spec/spec_helper.rb
Added SimpleCov. Looks good!
```
Finished in 2.05 seconds (files took 1.1 seconds to load)
309 examples, 0 failures
Coverage report generated for RSpec to /Users/sean/src/rb/gems/ransack/coverage. 1332 / 1372 LOC (97.08%) covered.
```
> added SimpleCov

- lib/ransack.rb
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- lib/ransack/helpers/form_builder.rb
- lib/ransack/nodes/attribute.rb
- lib/ransack/nodes/grouping.rb
Here are some quick fixes for the Ruby-level warnings that we see in our app. Thanks!
> Ruby Warnings

- lib/ransack/visitor.rb
- spec/ransack/adapters/active_record/base_spec.rb
- spec/support/schema.rb
https://github.com/activerecord-hackery/ransack/pull/851
> merge of PR 851

- README.md
It is seems I have found another solution to solve problem with Postgresql and distinct: true.
> Doc for distinct improve

- lib/polyamorous/activerecord_5.2.1_ruby_2/join_dependency.rb
In the current master, an error occurs when performing a specific join process in AR 5.2.1(My bad!).
Reproduce script is following.
```
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem "rails", "5.2.1.rc1"
gem "byebug"
gem "ransack", github: "activerecord-hackery/ransack", require: false
gem "sqlite3"
end
require "active_record"
require "ransack"
require "minitest/autorun"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Schema.define do
create_table "set_adopted_books", force: :cascade do |t|
t.bigint "adopted_book_set_id"
end
create_table "adopted_book_sets", force: :cascade do |t| …
```
> Do not override `join_constraints`

- spec/ransack/adapters/active_record/base_spec.rb
- spec/ransack/helpers/form_helper_spec.rb
- spec/support/schema.rb
Now that #search is deprecated update test to remove all the warnings from travis
> Change #search for #ransack on tests

- lib/ransack/adapters/active_record/context.rb
- spec/ransack/adapters/active_record/context_spec.rb
- spec/support/schema.rb
Fix this issue
https://github.com/activerecord-hackery/ransack/issues/925
> fix undefined method eq for Arel::Nodes::Equality by deep call left

- .gitignore
- lib/ransack/version.rb
- ransack.gemspec
> Ease Active Record dependency

- lib/ransack/adapters/active_record/ransack/translate.rb
- lib/ransack/translate.rb
Private does nothing to class methods, move all class methods within a `class << self` block and make those methods private
Other minor code style fixes
> Fix useless private  for class methods

- lib/ransack/context.rb
`str.splice` was being called twice in the same method to get the segments, remove one of these calls
Other small codestyle fixes
> Fix calling String#split twice to get segments

- polyamorous/lib/polyamorous/activerecord_6.1_ruby_2/join_association.rb
- polyamorous/lib/polyamorous/activerecord_6.1_ruby_2/join_dependency.rb
- polyamorous/lib/polyamorous/activerecord_6.1_ruby_2/reflection.rb
Maybe this is too early but this would allow some bare testing of current Rails master.
> Allow testing out current Rails master

- ransack.gemspec
> Fix incompatibility with Dependabot

- .travis.yml
This is a temporary pull request to test in travis world
> Update .travis.yml to test against ruby 2.6.4

- README.md
- lib/ransack/adapters/active_record/ransack/constants.rb
- lib/ransack/adapters/active_record/ransack/nodes/condition.rb
- lib/ransack/nodes/condition.rb
- lib/ransack/predicate.rb
- spec/ransack/predicate_spec.rb
Fix issue #82 'cont' not working on Oracle
> Fixes #82 Case Insensitive Searching

- lib/polyamorous/activerecord_5.2_ruby_2/reflection.rb
- spec/ransack/search_spec.rb
Reverts activerecord-hackery/ransack#1122
CI fails on merge to `master`
> Revert "Fixes polymorphic joins."

- lib/polyamorous/activerecord_5.2_ruby_2/reflection.rb
- spec/ransack/search_spec.rb
Reverts activerecord-hackery/ransack#1128
> Revert "Revert "Fixes polymorphic joins.""

- .travis.yml
To avoid duplicate CI checks on PR.
> Only run CI on pushes to master

- .travis.yml
- CHANGELOG.md
- lib/polyamorous/activerecord_6.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_6.1_ruby_2/join_dependency.rb
- lib/ransack/adapters/active_record/context.rb
- lib/ransack/adapters/active_record/ransack/context.rb
- lib/ransack/constants.rb
> Add Rails 6.1 support

- lib/ransack/search.rb
- spec/ransack/search_spec.rb
> Strip Leading & Trailing Whitespace Before Searching

- CHANGELOG.md
- lib/ransack/version.rb
Bump version to 2.4.0
CC @deivid-rodriguez
> Bump 2.4.0

- .github/FUNDING.yml
- README.md
I'm completing a few tasks that I need to setup Tidelift, like linking to their subscription in a FUNDING.yml file or linking to their coordinated disclosure plan for security issues.
> Links to Tidelift subscription

- spec/ransack/indirect_association_spec.rb
- spec/support/schema.rb
This adds a spec that should demonstrate the issue described in #1153.
> Add spec described in #1153.

- CHANGELOG.md
- lib/ransack/version.rb
I'd like to release 2.6.0 with some recent improvements.
> Get ready for 2.6.0 release

- CHANGELOG.md
I added changelog for the latest few releases in Github and then synchronized release notes with `CHANGELOG.md`.
> Synchronize latest versions changelog with Github releases

- ransack.gemspec
Adding David Rodríguez as a Ransack author.
- @deivid-rodriguez do you want you email also added? (not necessary)
- @radar @jonatack @ernie would you like your email addresses [removed from the gemspec](https://github.com/activerecord-hackery/ransack/blob/main/ransack.gemspec#L11) ?
> Add David Rodríguez as an author

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
> Workflows for automatic deployment of docs site

- docs/docusaurus.config.js
> Fix documentation site edit urls

- docs/docs/going-further/merging-searches.md
Just testing out the "Edit this page" functionality on the docs website:  it works great! 🚀 🎸
> Add full link to issue

- docs/docs/going-further/wiki-contributors.md
Put contributor list last in sidebar.
> Put contributor list last

- lib/polyamorous/activerecord_7.1_ruby_2/join_association.rb
- lib/polyamorous/activerecord_7.1_ruby_2/join_dependency.rb
- lib/polyamorous/activerecord_7.1_ruby_2/reflection.rb
Refer to #1192 and #1205 for the similar change to support 6.2.0.alpha
and 7.0.0.alpha
This commit should make cronjob CI green.
> Allow Ransack runs test against Rails main branch aka 7.1.0.alpha

- docs/docs/getting-started/simple-mode.md
- docs/docs/going-further/acts-as-taggable-on.md
- docs/docs/going-further/i18n.md
- spec/ransack/predicate_spec.rb
This PR is improved some wording and corrected some typos.
> Improve some wording and correct some typos

- .github/workflows/test.yml
> Improve CI

- docs/yarn.lock
Just to shush a security alert.
> Bump some doc deps

- docs/docs/going-further/polymorphic-search.md
It's not obvious how to search for namespaced polymorphic models. This addresses that with an example.
> Add namespaced example of Polymorphic search

- .github/workflows/cronjob.yml
- .github/workflows/deploy.yml
- .github/workflows/rubocop.yml
- .github/workflows/test-deploy.yml
- .github/workflows/test.yml
* CI on latest Ruby patch levels.
* CI on ubuntu 22.04
> Misc CI bumps

- ransack.gemspec
After the discussion in #1545, I'm sending this quick update.
> Update activerecord and activesupport version

- lib/ransack/nodes/condition.rb
- lib/ransack/nodes/value.rb
- spec/ransack/search_spec.rb
- spec/support/schema.rb
> Fix enum support

- lib/ransack/locale/uk.yml
Added Ukrainian translation of English version 
https://github.com/activerecord-hackery/ransack/blob/main/lib/ransack/locale/en.yml
> Add Ukrainian translation locale

- README.md
Links to AI generated docs and a cheatsheet by @raghubetina
> Add alternative documentation links

- ransack.gemspec
Part of https://github.com/activerecord-hackery/ransack/issues/1634
> Improve RubyGems description

- CHANGELOG.md
Updated CHANGELOG to reflect new versioning and support changes.
> Revise CHANGELOG for versioning and support updates
